_enabled_ordered = ["Alphabet", "Navigation", "NavigationNon", "Numbers", "Punctuation", "Keyboard", "CasterRule", "HardwareRule", "MouseAlternativesRule", "WindowManagementRule", "DouglasGridRule", "RainbowGridRule", "SudokuGridRule", "HMCRule", "HMCConfirmRule", "HMCDirectoryRule", "HMCHistoryRule", "HMCLaunchRule", "HMCSettingsRule", "HistoryRule", "ChainAlias", "Alias", "BringRule", "Again", "GrammarActivatorRule", "HooksActivationRule", "TerminalRule", "DesktopEnvironment", "EmacsRule", "TmuxRule", "TransformersActivationRule", "FirefoxRule", "TextManipulation"]
_internal = ["GrammarActivatorRule", "HooksActivationRule", "TransformersActivationRule", "ManualGrammarReloadRule"]

[whitelisted]
AcrobatRule = true
Again = true
Alias = true
Alphabet = true
AtomRule = true
Bash = true
BringRule = true
CPP = true
CSSTreeRule = true
CSharp = true
CasterRule = true
ChainAlias = true
ChromeRule = true
Dart = true
DesktopEnvironment = true
DouglasGridRule = true
DragonRule = true
EclipseCCR = true
EclipseRule = true
EmacsPythonRule = true
EmacsRule = true
ExcelRule = true
FileDialogueRule = true
FirefoxRule = true
FlashDevelopRule = true
FoxitRule = true
GitBashRule = true
GitHubDeskRule = true
GitterRule = true
Go = true
HMCConfirmRule = true
HMCDirectoryRule = true
HMCHistoryRule = true
HMCLaunchRule = true
HMCRule = true
HMCSettingsRule = true
HTML = true
HardwareRule = true
Haxe = true
HistoryRule = true
IERule = true
Java = true
JavaNon = true
Javascript = true
JetbrainsRule = true
KDiff3Rule = true
LaTeX = true
LegionGridRule = true
LyxRule = true
MSTeamsRule = true
MSVCRule = true
MSWordRule = true
Markdown = true
Matlab = true
MatlabNon = true
MouseAlternativesRule = true
NPPRule = true
Navigation = true
NavigationNon = true
Numbers = true
OutlookRule = true
Prolog = true
PrologNon = true
Punctuation = true
Python = true
PythonNon = true
RStudioRule = true
RainbowGridRule = true
Rlang = true
Rust = true
RustNon = true
SQL = true
SQLDeveloperRule = true
SSMSRule = true
SikuliManagementRule = true
SikuliRule = true
SpellingWindowRule = true
SublimeRule = true
SudokuGridRule = true
SyncDirsRule = true
TerminalRule = true
TextManipulation = true
TmuxRule = true
TotalCommanderRule = true
TyporaRule = true
UnityRule = true
VHDL = true
VHDLnon = true
VSCodeCcrRule = true
VSCodeNonCcrRule = true
VisualStudioRule = true
VoiceDevCommands = true
WebexTeamsRule = true
WindowManagementRule = true
WindowsSpeechRecognitionRule = true
fmanRule = true
JiraRule = true
CasterMicRule = false
Keyboard = true
